In [2]:
import torch
import d2l

In [7]:
## total no of elements in a tensor using numel

In [4]:
t=torch.arange(10)

In [5]:
t

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
t.numel()

10

In [9]:
t.shape

torch.Size([10])

In [11]:
t.size()

torch.Size([10])

In [12]:
a=torch.tensor([1,2,3,4])
b=torch.tensor([2,1,2,1])

In [13]:
a+b

tensor([3, 3, 5, 5])

In [14]:
a-b

tensor([-1,  1,  1,  3])

In [15]:
a*b

tensor([2, 2, 6, 4])

In [16]:
a/b

tensor([0.5000, 2.0000, 1.5000, 4.0000])

In [17]:
a**b

tensor([1, 2, 9, 4])

In [18]:
b[2]=0

In [19]:
a/b

tensor([0.5000, 2.0000,    inf, 4.0000])

In [20]:
## concatenate multiple tensors

In [22]:
torch.cat((a,b), axis=0)

tensor([1, 2, 3, 4, 2, 1, 0, 1])

In [26]:
x=(a==b)

In [27]:
x

tensor([False, False, False, False])

In [34]:
a=torch.arange(2).reshape((1,2))
b=torch.arange(3).reshape((3,1))

In [35]:
a

tensor([[0, 1]])

In [36]:
b

tensor([[0],
        [1],
        [2]])

In [37]:
a+b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [39]:
z=torch.zeros(3)
id(z)

124690228755600

In [40]:
x=torch.ones(3)
y=2*torch.ones(3)
z=x+y

In [41]:
id(z)

124690228753280

In [42]:
## Thus address of z changes, hence memory wasted

In [43]:
z=torch.zeros(3)
id(z)

124690228807616

In [44]:
x=torch.ones(3)
y=2*torch.ones(3)
z[:]=x+y

In [45]:
id(z)

124690228807616

In [46]:
## address remains same when we use slicing operation

In [49]:
a=torch.tensor([1])
a.item()

1

In [51]:
a=torch.tensor([[1,2],[3,4]])
a.cumsum(axis=0)

tensor([[1, 2],
        [4, 6]])

In [52]:
a.cumsum(axis=1)

tensor([[1, 3],
        [3, 7]])

In [54]:
a=torch.tensor([-1,2])
a.abs().sum()

tensor(3)

#### Autograd

In [111]:
x=torch.arange(4.0)

In [112]:
x

tensor([0., 1., 2., 3.])

In [113]:
x.requires_grad_(True)

tensor([0., 1., 2., 3.], requires_grad=True)

In [114]:
x.grad

In [115]:
y=2*torch.dot(x,x)

In [116]:
y.backward(retain_graph=True)

In [117]:
x.grad

tensor([ 0.,  4.,  8., 12.])

In [118]:
y.backward(retain_graph=True)

In [119]:
x.grad

tensor([ 0.,  8., 16., 24.])

In [120]:
y.backward(retain_graph=True)

In [121]:
x.grad

tensor([ 0., 12., 24., 36.])

In [122]:
z=3*torch.dot(x,x)

In [123]:
z.backward(retain_graph=True)

In [124]:
x.grad

tensor([ 0., 18., 36., 54.])

In [125]:
import torch

# Create tensors
x = torch.tensor([1.0], requires_grad=True)
w = torch.tensor([2.0], requires_grad=True)
b = torch.tensor([3.0], requires_grad=True)

# Perform a computation
y = w * x + b

# Perform backpropagation
y.backward()

# Check gradients
print(x.grad)  # Output: tensor([2.])
print(w.grad)  # Output: tensor([1.])
print(b.grad)  # Output: tensor([1.])

# Perform another computation
y2 = 2 * w * x + b

# Perform backpropagation again
y2.backward()

# Check gradients again (gradients accumulate)
print(x.grad)  # Output: tensor([4.])
print(w.grad)  # Output: tensor([2.])
print(b.grad)  # Output: tensor([2.])


tensor([2.])
tensor([1.])
tensor([1.])
tensor([6.])
tensor([3.])
tensor([2.])


In [126]:
import torch

# Create tensors
x = torch.tensor([1.0], requires_grad=True)
w = torch.tensor([2.0], requires_grad=True)
b = torch.tensor([3.0], requires_grad=True)

# Perform a computation
y = w * x + b

# Perform backpropagation
y.backward()

# Check gradients
print(x.grad)  # Output: tensor([2.])
print(w.grad)  # Output: tensor([1.])
print(b.grad)  # Output: tensor([1.])

x.grad.zero_()
w.grad.zero_()
b.grad.zero_()
# Perform another computation
y2 = 2 * w * x + b

# Perform backpropagation again
y2.backward()

# Check gradients again (gradients accumulate)
print(x.grad)  # Output: tensor([4.])
print(w.grad)  # Output: tensor([2.])
print(b.grad)  # Output: tensor([2.])


tensor([2.])
tensor([1.])
tensor([1.])
tensor([4.])
tensor([2.])
tensor([1.])


In [127]:
x

tensor([1.], requires_grad=True)

In [131]:
x.grad.zero_()
y=x*x
y.backward()
x.grad

tensor([2.])

In [135]:
x=torch.arange(5.0)
x.requires_grad=True

In [136]:
y=x*x

In [138]:
y.sum().backward(retain_graph=True)

In [139]:
x.grad

tensor([0., 2., 4., 6., 8.])

In [140]:
x.grad.zero_()

tensor([0., 0., 0., 0., 0.])

In [142]:
u=y.detach()
u

tensor([ 0.,  1.,  4.,  9., 16.])

In [144]:
v=u*x

In [145]:
v.sum().backward(retain_graph=True)

In [146]:
x.grad

tensor([ 0.,  1.,  4.,  9., 16.])